import * as fc from 'fast-check';
import { describe, it, expect } from 'vitest';

import {
  generateTraceparent,
  withTraceHeaders,
  isValidTraceparent,
  TRACEPARENT_REGEX,
} from '../middleware/trace-context.js';

/**
 * Property 8: Trace Context Header Injection
 *
 * For any response generated by the Mock_Engine, the response headers SHALL
 * include valid W3C trace context headers (`traceparent` and optionally
 * `tracestate`) enabling span correlation across the fetch boundary.
 *
 * W3C traceparent format: {version}-{trace-id}-{parent-id}-{trace-flags}
 *   - version: "00"
 *   - trace-id: 32 lowercase hex chars
 *   - parent-id: 16 lowercase hex chars
 *   - trace-flags: 2 lowercase hex chars
 *
 * **Validates: Requirements 12.3**
 */
describe('Feature: enterprise-frontend-monorepo, Property 8: Trace Context Header Injection', () => {
  it('every generated traceparent matches the W3C format', () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 1000 }), (_seed) => {
        const traceparent = generateTraceparent();

        // Must match the full W3C traceparent regex
        expect(traceparent).toMatch(TRACEPARENT_REGEX);
        expect(isValidTraceparent(traceparent)).toBe(true);

        // Verify structure: version-traceId-parentId-traceFlags
        const parts = traceparent.split('-');
        expect(parts).toHaveLength(4);
        expect(parts[0]).toBe('00'); // version
        expect(parts[1]).toHaveLength(32); // trace-id: 32 hex chars
        expect(parts[2]).toHaveLength(16); // parent-id: 16 hex chars
        expect(parts[3]).toHaveLength(2); // trace-flags: 2 hex chars

        // All hex parts are lowercase
        expect(parts[1]).toMatch(/^[0-9a-f]{32}$/);
        expect(parts[2]).toMatch(/^[0-9a-f]{16}$/);
        expect(parts[3]).toMatch(/^[0-9a-f]{2}$/);
      }),
      { numRuns: 100 },
    );
  });

  it('withTraceHeaders always includes a valid traceparent header', () => {
    fc.assert(
      fc.property(
        fc.dictionary(
          fc.stringMatching(/^[a-z][a-z0-9-]{0,20}$/),
          fc.string({ minLength: 1, maxLength: 50 }),
          { minKeys: 0, maxKeys: 5 },
        ),
        (existingHeaders) => {
          const headers = withTraceHeaders(existingHeaders);

          // traceparent must always be present and valid
          const traceparent = headers.get('traceparent');
          expect(traceparent).not.toBeNull();
          expect(isValidTraceparent(traceparent!)).toBe(true);

          // tracestate must be present
          const tracestate = headers.get('tracestate');
          expect(tracestate).not.toBeNull();
          expect(tracestate!.length).toBeGreaterThan(0);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('traceparent trace-id and parent-id are never all zeros', () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 1000 }), (_seed) => {
        const traceparent = generateTraceparent();
        const parts = traceparent.split('-');

        // W3C spec: trace-id must not be all zeros
        expect(parts[1]).not.toBe('0'.repeat(32));
        // W3C spec: parent-id must not be all zeros
        expect(parts[2]).not.toBe('0'.repeat(16));
      }),
      { numRuns: 100 },
    );
  });

  it('each invocation produces a unique traceparent (trace-id uniqueness)', () => {
    fc.assert(
      fc.property(fc.integer({ min: 2, max: 50 }), (count) => {
        const traceIds = new Set<string>();
        for (let i = 0; i < count; i++) {
          const traceparent = generateTraceparent();
          const traceId = traceparent.split('-')[1];
          traceIds.add(traceId);
        }
        // All generated trace-ids should be unique
        expect(traceIds.size).toBe(count);
      }),
      { numRuns: 100 },
    );
  });

  it('withTraceHeaders preserves all existing headers while adding trace context', () => {
    fc.assert(
      fc.property(
        fc.dictionary(
          fc.stringMatching(/^x-[a-z]{1,10}$/),
          // Use alphanumeric values to avoid Header API whitespace trimming behavior
          fc.stringMatching(/^[a-z0-9]{1,30}$/),
          { minKeys: 1, maxKeys: 5 },
        ),
        (existingHeaders) => {
          const headers = withTraceHeaders(existingHeaders);

          // All original headers should be preserved
          for (const [key, value] of Object.entries(existingHeaders)) {
            expect(headers.get(key)).toBe(value);
          }

          // Trace headers should also be present
          expect(headers.has('traceparent')).toBe(true);
          expect(headers.has('tracestate')).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });
});
